services:
  web:
    command: npm run dev
    environment:
      NODE_ENV: "development"
      LOG_LEVEL: "trace"
    volumes:
      - ../..:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
